(in-package clvm)

(defun lit-tests ()
  (let ((*vm* (new-vm)))
    (emit (new-lit-form (int-type (abc-lib *vm*)) 42))
    (vm-eval)
    (assert (= (data (vm-pop)) 42))))

(defun label-tests ()
  (let* ((*vm* (new-vm))
	 (int (int-type (abc-lib *vm*))))
    (emit (new-goto-op :foo))
    (emit (new-push-op int 1))
    (emit (new-label-op :foo))
    (emit (new-push-op int 2))
    (vm-eval)
    (assert (= (data (vm-pop)) 2))
    (assert (null (vm-pop)))))

(defun branch-tests ()
  (let* ((*vm* (new-vm))
	 (int (int-type (abc-lib *vm*))))
    (emit (new-push-op int 0))
    (emit (new-branch-op :false))
    (emit (new-push-op int 1))
    (emit (new-goto-op :end))
    (emit (new-label-op :false))
    (emit (new-push-op int 2))
    (emit (new-label-op :end))
    (vm-eval)
    (assert (= (data (vm-pop)) 2))
    (assert (null (vm-pop)))))

(defun all-tests ()
  (lit-tests)
  (label-tests)
  (branch-tests))
  
